Sphinx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('authenticate.urls')),
    path('admin/', admin.site.urls,),
    path('quiz/', include('quiz.urls')),
    path('sub/', include('subjective.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from .views import *
from . import views
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'quiz'


urlpatterns = [
    url(r'^leaderboard/$', views.LeaderBoard, name='leaderboard'),
    url(r'^$', view=index, name='index'),
    url(r'^quizzes/$', view=QuizListView.as_view(), name='quiz_index'),
    path('progress/', views.ProgressView, name='progress'),

    url(r'^category/$', view=CategoriesListView.as_view(), name='quiz_category_list_all'),
    url(r'^category/(?P<category_name>[\w|\W-]+)/$', view=ViewQuizListByCategory.as_view(), name='quiz_category_list_matching'),
    url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',view=QuizTake.as_view(), name='quiz_question'),
    #url(regex=r'^(?P<quiz_name>[\w-]+)/subtake/$',view=QuizSubTake.as_view(), name='quiz_question_sub'),
    #url(regex=r'^(?P<pk>[0-9]+)/subtake/$',view=QuizSubTake.as_view(), name='quiz_question_sub'),
    #path('', include('authenticate.urls')),
    #url(r'^(?P<ques_id>\d+)/submit/$', views.ques_ans, name='ques_ans'),
    #path(regex=r'^(?P<quiz_name>[\w-]+)/subtake/$', include('subjective.urls')),
]

subjective/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import *
from . import views

app_name = 'subjective'


urlpatterns = [
    url(r'^$', view=IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', view=DetailView.as_view(), name='detail'),
    url(r'^#/$', view=views.first, name='first'),
    url(r'^checksub/$', views.checksubanswer, name='checksubanswer'),
    #url(r'^check/$', views.displayans, name='displayans'),
    url(r'^(?P<answer>[\w.]+)/submitscore/$', views.updatemarks, name='updatemarks'),
    url(r'^(?P<uas>[\w.@+-]+)$', views.displayans, name='displayans'),
    # path(r'^(?P<pk>[0-9]+)/submit/$', views.ques_ans, name='ques_ans'),
    #url(r'^(?P<ques_id>\d+)/submit/$', views.ques_ans, name='ques_ans'),
    url(r'^abc/submit/(?P<ques_id>\d+)$', views.ques_ans, name='ques_ans'),

]

subjective/models.py
from django.db import models
from django.urls import reverse
from quiz.models import Question
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User



# Create your models here.



class QuestionSub(Question):

    def check_if_correct(self, guess):
        return False

    def get_answers(self):
        return False

    def get_answers_list(self):
        return False

    def answer_choice_to_string(self, guess):
        return str(guess)

    def get_absolute_url(self):
        return reverse('subjective:detail', kwargs={'pk', self.pk})

    #def __str__(self):
        #return self.content

    '''class Meta:
        verbose_name = "Subjective Question"
        verbose_name_plural = "Subjective Questions"'''




class AnswerSub(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    user_ans = models.CharField(verbose_name='userbyans', max_length=2000)
    question = models.ForeignKey(QuestionSub, on_delete=models.CASCADE)
    ans_text = models.CharField(max_length=3000, verbose_name='your answer')
    is_attempted = models.IntegerField(default=1)
    answermarks = models.IntegerField(default=0)

    def __str__(self):
        return self.ans_text


class Subscore(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    usersub = models.CharField(verbose_name='usersub', max_length=2000)
    subscore = models.IntegerField(verbose_name='userscore', default=0)

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list, widget=RadioSelect)

'''class EssayForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))'''

quiz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render,render_to_response
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import FormView
from .forms import QuestionForm
from .models import Quiz, Category,Sitting,Question,UserProgress
from subjective.models import Subscore
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from subjective.models import QuestionSub, AnswerSub ,Subscore
from mcq.models import Mcqscore
from django.http import HttpResponseRedirect, HttpResponse
from subjective import models

from django.urls import reverse_lazy, reverse
from mcq.models import Mcqscore

a = UserProgress()

def index(request):
    return render(request, 'index.html', {})


class QuizListView(ListView):
    model = Quiz

    def get_queryset(self):
        queryset = super(QuizListView, self).get_queryset()
        return queryset.filter(draft=False)


class CategoriesListView(ListView):
    model = Category


class ViewQuizListByCategory(ListView):
    model = Quiz
    template_name = 'view_quiz_category.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            category=self.kwargs['category_name']
        )

        return super(ViewQuizListByCategory, self).\
            dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewQuizListByCategory, self)\
            .get_context_data(**kwargs)

        context['category'] = self.category
        return context

    def get_queryset(self):
        queryset = super(ViewQuizListByCategory, self).get_queryset()
        return queryset.filter(category=self.category, draft=False)


class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'question.html'

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, url=self.kwargs['quiz_name'])
        if self.quiz.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            self.sitting = Sitting.objects.user_sitting(request.user,
                                                        self.quiz)
        if self.sitting is False:
            return render(request, 'single_complete.html')

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=QuestionForm):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()
        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        #progress, c = Progress.objects.get_or_create(user=self.request.user)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1, self.question)
            #progress.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
           # progress.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
        }

        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] =\
                self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] =\
                self.sitting.get_incorrect_questions

        if self.quiz.exam_paper is False:
            self.sitting.delete()

        return render(self.request, 'result.html', results)


@login_required
def ProgressView(request):
    from subjective.views import createobject
    createobject()
    curr_user = request.user
    marks = 0
    if len(Subscore.objects.all()):
        try:
            a2 = Subscore.objects.get(user=curr_user)
            if a2:
                marks += a2.subscore
        except:
            a2 = Subscore()
            a2.user = request.user
            a2.usersub = request.user
            a2.subscore = 0
            a2.save()
            marks += a2.subscore


    if len(Mcqscore.objects.all()):
        try:
            a1 = Mcqscore.objects.get(user=curr_user)
            if a1:
                marks += a1.mcqscore
        except:
            a1 = Mcqscore()
            a1.user=request.user
            a1.usermcq=request.user
            a1.mcqscore = 0
            a1.save()
            marks += a1.mcqscore
    return render(request, 'progress.html', {"user": request.user, "marks":marks})

def LeaderBoard(request):
    from subjective.views import createobject
    createobject()
    rank = Subscore.objects.all()
    obj = Mcqscore.objects.all()

    kj=0
    print(obj)
    if len(rank)>0:
        for i in rank:
            print("j")

            for j in obj:
                if j.usermcq == i.usersub:
                    print(rank[kj].subscore)
                    rank[kj].subscore += j.mcqscore
                    print(rank[kj].subscore)
            kj+=1
        newlist = sorted(rank, key=lambda x: x.subscore, reverse=True)
    elif len(obj)>0:
        for i in obj:
            print("j")
            for j in rank:
                if j.usersub == i.usermcq:
                    #print(rank[kj].subscore)
                    obj[kj].mcqscore += j.subscore
                    #print(rank[kj].subscore)
            kj += 1
        newlist = sorted(obj, key=lambda x: x.mcqscore, reverse=True)

    # To return a new list, use the sorted() built-in function...
    if (len(obj)==0 and len(rank)==0):
        return render(request, 'leaderboard1.html')
    print(newlist)
    return render(request,'leaderboard.html', {'newlist':newlist})

subjective/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import QuestionSub, AnswerSub, Question, Subscore
from django.http import HttpResponseRedirect
from . import models
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from mcq.models import Mcqscore
listofuserobject = {}
count = models.QuestionSub.objects.all().count()
c = 1
ques_list2 = []
ques_list = QuestionSub.objects.all()
list1 = {}
list3 = {}
list4 = {}
users = User.objects.all()
list2 = []
onetime = 0


def createobject():

    if not len(Subscore.objects.all()):
        listtemp = Subscore.objects.all()
        listofuserobject.clear()
        for j in listtemp:
            listofuserobject.update({j.usersub: j.subscore})
        for i in users:
            obh = Mcqscore()
            obj = Subscore()
            obh.user = obj.user = i
            obh.usermcq = obj.usersub = i.username
            obj.subscore = obh.mcqscore = 0
            obh.save()
            obj.save()
            listofuserobject.update({obj.usersub: obj.subscore})
    else:
        listtemp = Subscore.objects.all()
        listofuserobject.clear()
        for j in listtemp:
            listofuserobject.update({j.usersub: j.subscore})

        for i in users:
            if i.username not in listofuserobject.keys():
                print(i.username)
                obh = Mcqscore()
                obj = Subscore()
                obh.user = obj.user = i
                obh.usermcq = obj.usersub = i.username
                obj.subscore = obh.mcqscore = 0
                obh.save()
                obj.save()
                listofuserobject.update({obj.usersub: obj.subscore})


class IndexView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = QuestionSub
    template_name = 'subjective/detail.html'




def first(request):
    ques_list = QuestionSub.objects.all()
    import random
    hh=len(ques_list)
    data = list(range(0, hh))
    random.shuffle(data)
    k=0
    for i in ques_list:
        ques_list2.append(ques_list[data[k]])
        k += 1
    return HttpResponseRedirect(reverse('subjective:detail', args=(ques_list2[0].id,)))


def ques_ans(request, ques_id):

    kl=0
    for i in ques_list2:
        kl+=1
        j = request.user
        if i in list1.keys() and j == list1[i]:
            continue
        else:
            if request.method == "POST":
                choice = request.POST['answer']
                ans = AnswerSub()
                ans.user = request.user
                ans.ans_text = choice
                ans.user_ans =u= request.user
                ans.question = i
                ans.is_attempted += 1
                print(list1)
                if ques_id in list3.keys() and u == list3[ques_id]:
                    print("d")
                    kl-=1
                    #return HttpResponseRedirect(reverse('subjective:detail', args=(ques_list2[kl].id,)))
                else:
                    list1[i] = j
                    if j not in list4.keys():
                        list4[j] = 1
                    else:
                        list4[j] +=1
                    ans.save()
                    j = request.user
                    print(j)
                    list3[ques_id]=j


                if list4[j] < len(ques_list):
                    return HttpResponseRedirect(reverse('subjective:detail', args=(ques_list2[kl].id,)))
        a = AnswerSub.objects.filter(user_ans=ans.user_ans)
        return render(request, 'quizover.html', {'a': a})



def checksubanswer(request):
    users = User.objects.all()
    return render(request, 'subjective/checksubanswer.html', {'user' : users })


def displayans(request, uas):
    answer1 = AnswerSub.objects.filter(user_ans=uas)
    return render(request,'subjective/usersubanswer.html',{'answer' : answer1,'uas':uas })

def updatemarks(request,answer):
        ans = AnswerSub.objects.get(pk=answer)
        if ans in list2:
            None
        else:
            list2.append(ans)
            if request.method == 'GET':
                mq = request.GET['marks']
            for i in listofuserobject:
                if i == ans.user_ans:
                    listofuserobject[i]+=int(mq)
                    kkk = Subscore.objects.get(usersub=i)
                    ans.answermarks=int(mq)
                    ans.save()
                    kkk.subscore=listofuserobject[i]
                    kkk.save()
        return render(request, 'subjective/checksubanswer.html', {'user' : users })

quiz/templates/subjective/checksubanswer.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <head>
  <title>Leaderboard</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: floralwhite;
}
        tr:nth-child(odd) {
  background-color: lemonchiffon;
}
</style>
</head>
<body><br>
    <br>
    <br>
    <div><header>Click To Check And update Score</header>
    <table>
        {% for i in user %}
            <tr><td><a href="{% url 'subjective:displayans' i %}">{{ i }}</a></td><br></tr>
        {% endfor %}
    </table>
    </div>
</body>
{% endblock %}

quiz/templates/subjective/detail.html
{% extends 'base.html' %}
{% block title %}{{ question.pk }}{% endblock %}
{% block questions_active %}active{% endblock %}
{% block body %}
<div style="font-weight: bold" id="quiz-time-left"></div>

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="https://drive.google.com/open?id=1hDHvuyO5vL7sRAedykYNDzScgoqAMQEe">
    <link rel="icon" href="https://drive.google.com/open?id=1hDHvuyO5vL7sRAedykYNDzScgoqAMQEe" type="image/x-icon">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <script src="{% static 'quiz/js/timer.js' %}"></script>

</head>

<br>
    <br>
    <br>
<div class="container-fluid songs-container">
    <div class="col-sm-4 col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                {% if questionsub.content %}
                    <pre>Q{{ questionsub.pk }}. {{ questionsub.content }}</pre>
                {% else %}
                    <h3>No Question to display</h3>
                {% endif %}
                {% if questionsub.figure %}
                    <div class="panel-body" >
                        <img src="{{ questionsub.figure.url }}" class="img-responsive" >
                    </div>

                {% endif %}
                {% if question.ques_link %}
                    <div class="panel-default" >
                        <a href="{{ questionsub.category }}">link</a>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>
    <form action="{% url 'subjective:ques_ans' questionsub.id %}" class="form-horizontal" method="post">
        {% csrf_token %}
        <input name="answer" type="text" class="form-control" placeholder="Enter Answer">
        <button type="submit" class="btn btn-primary">Submit</button> <!-- jo input wala hai wohi post me pass ho rha through submit button-->
    </form>
</div>

{% endblock %}

quiz/templates/subjective/usersubanswer.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <head>
    <title>Leaderboard</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>

     <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: floralwhite;
}
        tr:nth-child(odd) {
  background-color: lemonchiffon;
}
</style>
    </head>
    <body><br>
    <br>
    <br>
    <div>
    <table style="width:100%">
    <tr>
        <th>Question</th>
        <th>Answer</th>
        <th>Marks</th>
        <th>Marks you give</th>
    </tr>
        <div>
        <p style="background-color: cadetblue">User::{{ uas }}</p>
        {% for i in answer %}
            <form action="{% url 'subjective:updatemarks' i.pk %}" method="GET">
            <tr>
                <td>{{ i.question }}</td>
                <td>{{ i.ans_text }}</td>
                <td>{{ i.question.marks }}</td>
                <td><input name="marks" type="text" class="form-control" placeholder="{{ i.answermarks }}"></td>
                {% if i.answermarks == 0 %}
                <td> <input class="bottom-left" type="submit" value="Submit this score"/></td>
                {% endif %}
            </tr>
            </form>
        {% endfor %}
        </div>
    <div class="bottom">

    </div>
    </table>
    </div>
    </body>
{% endblock %}