Sphinx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('authenticate.urls')),
    path('admin/', admin.site.urls,),
    path('quiz/', include('quiz.urls')),
    path('sub/', include('subjective.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from .views import *
from . import views
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
app_name = 'quiz'


urlpatterns = [
    url(r'^leaderboard/$', views.LeaderBoard, name='leaderboard'),
    url(r'^$', view=index, name='index'),
    url(r'^quizzes/$', view=QuizListView.as_view(), name='quiz_index'),
    path('progress/', views.ProgressView, name='progress'),

    url(r'^category/$', view=CategoriesListView.as_view(), name='quiz_category_list_all'),
    url(r'^category/(?P<category_name>[\w|\W-]+)/$', view=ViewQuizListByCategory.as_view(), name='quiz_category_list_matching'),
    url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',view=QuizTake.as_view(), name='quiz_question'),
    #url(regex=r'^(?P<quiz_name>[\w-]+)/subtake/$',view=QuizSubTake.as_view(), name='quiz_question_sub'),
    #url(regex=r'^(?P<pk>[0-9]+)/subtake/$',view=QuizSubTake.as_view(), name='quiz_question_sub'),
    #path('', include('authenticate.urls')),
    #url(r'^(?P<ques_id>\d+)/submit/$', views.ques_ans, name='ques_ans'),
    #path(regex=r'^(?P<quiz_name>[\w-]+)/subtake/$', include('subjective.urls')),
]

subjective/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import *
from . import views

app_name = 'subjective'


urlpatterns = [
    url(r'^$', view=IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', view=DetailView.as_view(), name='detail'),
    url(r'^#/$', view=views.first, name='first'),
    url(r'^checksub/$', views.checksubanswer, name='checksubanswer'),
    #url(r'^check/$', views.displayans, name='displayans'),
    url(r'^(?P<answer>[\w.]+)/submitscore/$', views.updatemarks, name='updatemarks'),
    url(r'^(?P<uas>[\w.@+-]+)$', views.displayans, name='displayans'),
    # path(r'^(?P<pk>[0-9]+)/submit/$', views.ques_ans, name='ques_ans'),
    #url(r'^(?P<ques_id>\d+)/submit/$', views.ques_ans, name='ques_ans'),
    url(r'^abc/submit/(?P<ques_id>\d+)$', views.ques_ans, name='ques_ans'),

]

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list, widget=RadioSelect)

'''class EssayForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))'''

quiz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render,render_to_response
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import FormView
from .forms import QuestionForm
from .models import Quiz, Category,Sitting,Question,UserProgress
from subjective.models import Subscore
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from subjective.models import QuestionSub, AnswerSub ,Subscore
from mcq.models import Mcqscore
from django.http import HttpResponseRedirect, HttpResponse
from subjective import models

from django.urls import reverse_lazy, reverse
from mcq.models import Mcqscore

a = UserProgress()

def index(request):
    return render(request, 'index.html', {})


class QuizListView(ListView):
    model = Quiz

    def get_queryset(self):
        queryset = super(QuizListView, self).get_queryset()
        return queryset.filter(draft=False)


class CategoriesListView(ListView):
    model = Category


class ViewQuizListByCategory(ListView):
    model = Quiz
    template_name = 'view_quiz_category.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            category=self.kwargs['category_name']
        )

        return super(ViewQuizListByCategory, self).\
            dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewQuizListByCategory, self)\
            .get_context_data(**kwargs)

        context['category'] = self.category
        return context

    def get_queryset(self):
        queryset = super(ViewQuizListByCategory, self).get_queryset()
        return queryset.filter(category=self.category, draft=False)


class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'question.html'

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, url=self.kwargs['quiz_name'])
        if self.quiz.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            self.sitting = Sitting.objects.user_sitting(request.user,
                                                        self.quiz)
        if self.sitting is False:
            return render(request, 'single_complete.html')

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=QuestionForm):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()
        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        #progress, c = Progress.objects.get_or_create(user=self.request.user)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1, self.question)
            #progress.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
           # progress.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
        }

        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] =\
                self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] =\
                self.sitting.get_incorrect_questions

        if self.quiz.exam_paper is False:
            self.sitting.delete()

        return render(self.request, 'result.html', results)


@login_required
def ProgressView(request):
    from subjective.views import createobject
    createobject()
    curr_user = request.user
    marks = 0
    if len(Subscore.objects.all()):
        try:
            a2 = Subscore.objects.get(user=curr_user)
            if a2:
                marks += a2.subscore
        except:
            a2 = Subscore()
            a2.user = request.user
            a2.usersub = request.user
            a2.subscore = 0
            a2.save()
            marks += a2.subscore


    if len(Mcqscore.objects.all()):
        try:
            a1 = Mcqscore.objects.get(user=curr_user)
            if a1:
                marks += a1.mcqscore
        except:
            a1 = Mcqscore()
            a1.user=request.user
            a1.usermcq=request.user
            a1.mcqscore = 0
            a1.save()
            marks += a1.mcqscore
    return render(request, 'progress.html', {"user": request.user, "marks":marks})

def LeaderBoard(request):
    from subjective.views import createobject
    createobject()
    rank = Subscore.objects.all()
    obj = Mcqscore.objects.all()

    kj=0
    print(obj)
    if len(rank)>0:
        for i in rank:
            print("j")

            for j in obj:
                if j.usermcq == i.usersub:
                    print(rank[kj].subscore)
                    rank[kj].subscore += j.mcqscore
                    print(rank[kj].subscore)
            kj+=1
        newlist = sorted(rank, key=lambda x: x.subscore, reverse=True)
    elif len(obj)>0:
        for i in obj:
            print("j")
            for j in rank:
                if j.usersub == i.usermcq:
                    #print(rank[kj].subscore)
                    obj[kj].mcqscore += j.subscore
                    #print(rank[kj].subscore)
            kj += 1
        newlist = sorted(obj, key=lambda x: x.mcqscore, reverse=True)

    # To return a new list, use the sorted() built-in function...
    if (len(obj)==0 and len(rank)==0):
        return render(request, 'leaderboard1.html')
    print(newlist)
    return render(request,'leaderboard.html', {'newlist':newlist})

quiz/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="https://drive.google.com/open?id=1hDHvuyO5vL7sRAedykYNDzScgoqAMQEe">
    <link rel="icon" href="https://drive.google.com/open?id=1hDHvuyO5vL7sRAedykYNDzScgoqAMQEe" type="image/x-icon">
    <title >{% block title %}Sphinx{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="{% static 'quiz/js/main.js' %}"></script>

</head>
<body><br>
    <br>
    <br>
    <div class="navbar navbar-inverse navbar-fixed-top opaque-navbar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand"  href="{% url 'home' %}">Sphinx</a> <!--add karna hai homepage ka link-->
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="navMain">
            <ul class="nav navbar-nav pull-right">

                <li>
                    <a onclick="location.href='{% url 'admin:index' %}'">Admin Login</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'quiz:leaderboard' %}">
                            <span class="glyphicon glyphicon-list-alt"></span>LeaderBoard
                        </a>
                    </li>
                    <li >
                        <a href="{% url 'quiz:progress' %}">Progress</a>
                    </li>
                    <li >
                        <a href="{% url 'password_change' %}">Change Password</a>
                    </li>
                    <li class="">
                        <a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                {% else %}
                    <li >
                       <a href="{% url 'signup' %}">SignUp</a>
                    </li>
                    <li >
                       <a href="{% url 'login' %}">Login</a>
                    </li>

                {% endif %}
            </ul>
        </div>

    </div>
    </div>
{% block body %}
{% endblock %}
</body>
</html>

quiz/templates/correct_answer.html
{% load i18n %}
<br>
    <br>
    <br>
{% if previous.answers %}

  {% if user_was_incorrect %}
    <div class="alert alert-error">
  	  <strong>{% trans "You answered the above question incorrectly" %}</strong>
    </div>
  {% endif %}

  <table class="table table-striped table-bordered">
    <tbody>
  	  {% for answer in previous.answers %}
        {% if answer.correct %}
  	    <tr class="success">
  		  <td>{{ answer.content }}</td>
  		  <td><strong>{% trans "This is the correct answer" %}</strong></td>
        {% else %}
  		<tr>
      	  <td>{{ answer.content }}</td>
  		  <td>
  			{% if previous.question_type.MCQuestion %}
  			  {% if answer.id|add:"0" == previous.previous_answer|add:"0" %}
  			    {% trans "This was your answer." %}
  			  {% endif %}
  			{% endif %}
  		  </td>
  	  {% endif %}
  	    </tr>
  	{% endfor %}
    </tbody>
  </table>
{% endif %}

quiz/templates/home.html
<!DOCTYPE html>
<head>
{% extends 'base.html' %}

</head>
{% block body %}
<body   {% load staticfiles %}><br>
    <br>
    <br>
    {% load admin_urls %}



    {% if user.is_authenticated %}
        <div class="bg-text">
        <h2>Welcome</h2>
        <h1 style="font-size:50px">{{ user.username }}</h1>
        </div>
        <div class="bg-text1">
         <p>
            <strong>Total User registered yet :</strong>{{ count }}<strong></strong>
         </p>
            <button type="button" class="btn btn-success" onclick="location.href='{% url 'quiz:index' %}'" >Go to Quiz</button>

        </div>


    {% else %}
         <div class="text-center"><p class="navbar-brand" style="color: brown">
             <p>
        <strong>Total User registered yet :</strong>{{ count }}<strong> ! You will be the Next</strong>
    </p></div><br>
        <br>

    <div class="bg-text2 col-md-8 col-md-offset-2 text-center fh5co-heading animate-box fadeInUp animated-fast">

        <div ><h1 class="glow" >Sphinx</h1></div>
					<p>
    Sphinx 2k19, like a mystery has a surface innocence, surprise, the revelation of a concealed meaning and the catharsis of solution.

        <p>SPHINX , being the cryptic extravaganza it is, is one of the most popular events of the tech
fest Avishkar. It draws participation across all streams, departments and years, with 1000+
students battling it out for the glory.</p>
    </div>
    {% endif %}
</body>
{% endblock %}

quiz/templates/index.html
{% extends 'base.html' %}
{% block body %}<br>
    <br>
    <br>
<div class="question-container container-fluid" >
    <div class="col-sm-12">
        <h3>Hello {{ user.username }}'</h3>
    </div>
    <div class="col-sm-6 col-sm-offset-3">
  <div class="panel panel-default">
    <pre>
        <h2>Rules & Regulations:</h2>
        1.All Questions Are Compulsory.
        2.You Cannot Submit Answer twice.
            Subjective- first submission will only be accepted and updated.
        3.Admin decision is final.
        4.Electronic gadgets are prohibited.
        5.All the Best!
    </pre>
  </div>
        <div class="col-sm-12" align="right">
            <br>

                <button onclick="location.href='{% url 'quiz:quiz_category_list_all'  %}'" type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-arrow-right"></span>&nbsp; Start Quiz
                </button>
            </a>
        </div>
</div>
</div>
{% endblock %}

quiz/templates/leaderboard.html
{% extends "base.html" %}
{% block body %}
<head>
  <title>Leaderboard</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: floralwhite;
}
        tr:nth-child(odd) {
  background-color: lemonchiffon;
}
</style>
</head>

<body><br>
    <br>
    <br>
<div class="container-fluid">
    <table>
    <tr style="background-color:chocolate">
        <th>Rank</th>
        <th>UserName</th>
        <th>Marks</th>
    </tr>

        {% for i in newlist %}
            <tr>
                {% if i.usermcq %}
                     <td>{{ forloop.counter }}</td>
                    <td>{{ i.usermcq }}</td>
                    <td>{{ i.mcqscore }}</td>
                {% else %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ i.usersub }}</td>
                    <td>{{ i.subscore }}</td>
                {% endif %}
            </tr>
        {% endfor %}

    </table>
</div>
</body>

{% endblock %}

quiz/templates/leaderboard1.html
{% extends "base.html" %}
{% block body %}
<head>
  <title>Leaderboard</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: floralwhite;
}
        tr:nth-child(odd) {
  background-color: lemonchiffon;
}
</style>
</head>

<body><br>
    <br>
    <br>
<div class="alert alert-danger">
  <strong>INFO!</strong> No User Has Submitted any question or marks has not been alloted.
</div>
<div class="container-fluid">
    <table>
    <tr style="background-color:chocolate">
        <th>Rank</th>
        <th>UserName</th>
        <th>Marks</th>
    </tr>

    </table>
</div>
</body>

{% endblock %}

quiz/templates/progress.html
{% extends "base.html" %}
{% block body %}<br>
    <br>
    <br>
    <div class="bg-text1">
    <p>Your Marks {{ marks }} <br> Test given by:{{ user }}</p>
    </div>
{% endblock %}

quiz/templates/question.html
{% extends "base.html" %}
{% load i18n%}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}
<head>

</head>
{% block body %}
    <body class="text-center"><br>
    <br>
    <br>
            <div class="align-middle" >

    <div  class="col-sm-4 col-md-3">
{% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>

  {% if previous.previous_outcome %}
	<div class="alert alert-success">
  {% else %}
	<div class="alert alert-warning">
  {% endif %}
  	  <p><small>
		{% trans "Your answer was" %} </small>
		<strong>
		  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
		</strong>
	  </p>

	</div>

	{% include 'correct_answer.html' %}

	<p><strong>{% trans "Explanation" %}:</strong></p>
	<div class="well " style="background-color: #fcf8e3;">
	  <p>{{ previous.previous_question.explanation }}</p>
	</div>

	<hr>

{% endif %}

<br>
<div class="bg-text3">
{% if question %}
    <div>
    </div>

    {% if progress %}

    <div>
    {% trans "Question" %} {{ progress.0|add:1 }} {% trans "of" %} {{ progress.1 }}
    </div>
        <br>
    {% endif %}

    <p>
      <small class="muted">{% trans "Question category" %}:</small>
      <strong>{{ question.category }}</strong>
    </p>
    <p class="lead">{{ question.content }}</p>
    {% if question.question_link != '0'%}
        <a href="{{ question.question_link }}">LINK </a>
    {% endif %}
    {% if question.figure %}
        <img height="200px" width="266px"  src="{{ question.figure.url }}" alt="{{ question.content }}" />

    {% endif %}
<br>
    <hr>
    <form action="" method="POST">{% csrf_token %}
      <input type=hidden name="question_id" value="{{ question.id }}">

      <ul class="list-group">

        {% for answer in form.answers %}
          <li class="list-group-item">
            {{ answer }}
          </li>
        {% endfor %}


      </ul>
        {% if progress.0|add:1 == progress.1 %}
        <input type="submit" value={% trans "Submit" %} class="btn btn-large btn-block btn-warning" >
        {% else %}
            <input type="submit" value={% trans "Next" %} class="btn btn-large btn-block btn-warning" >
        {% endif %}
    </form>



{% endif %}

<hr>
        </div>
        </div>
            </div>
    </body>
{% endblock %}

quiz/templates/quizover.html
{% extends 'base.html' %}
{% block body %}<br>
    <br>
    <br>
    <h3>Welcome {{ user.username }}</h3>
    <h4>The Quiz is Over</h4><br>
    <br>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'quiz:quiz_category_list_all'  %}'">{{ cat.category }}
        Quiz List</button>
    <br>
    {% if user.is_authenticated %}
        {% for b in a %}
            <p>
            {{ b.ans_text  }} by {{ b.user_ans }}
            </p>

        {% endfor %}

    {% endif %}
{% endblock %}

quiz/templates/result.html
{% extends "base.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title}} {% endblock %}
{% block description %} {% trans "Exam Results for" %} {{ quiz.title }} {% endblock %}

{% block body %}<br>
    <br>
    <br>
    <div>
           <button type="button" class="btn btn-primary" onclick="location.href='{% url 'quiz:quiz_category_list_all'  %}'">{{ cat.category }}
        Quiz List</button>
    </div>
  {% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>
  <p>Your answer was
	<strong>
	  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
	</strong>
  </p>
  {% include 'correct_answer.html' %}
  <p><strong>{% trans "Explanation" %}:</strong></p>
  <div class="well " style="background-color: #fcf8e3;">
    <p>{{ previous.previous_question.explanation }}</p>
  </div>
  <hr>

  {% endif %}

  {% if max_score %}

  <div>
	<h2>{% trans "Exam results" %}</h2>
	<p>
	  <small class="muted">{% trans "Exam title" %}: </small>
	  <strong>{{ quiz.title }}</strong></p>

	<p class="lead">
	  {% trans "You marks : " %} {{ score }} {% trans "Total questions: " %} {{ max_score }}, {% trans "giving you" %} {{ percent }} {% trans "percent correct" %}
	</p>

	{% if quiz.pass_mark %}
	<hr>
        <p class="lead">{{ sitting.result_message }}</p>
	<hr>

	{% endif %}

	<p>{% trans "Review the questions below and try the exam again in the future"%}.</p>

	{% if user.is_authenticated %}

	  <p>{% trans "The result of this exam will be stored in your progress section so you can review and monitor your progression" %}.</p>

	{% endif %}
  </div>


  {% endif %}


  <hr>

  {% if possible %}

  <p class="lead">
	{% trans "Your session score is" %} {{ session }} {% trans "out of a possible" %} {{ possible }}
  </p>

  <hr>

  {% endif %}

  {% if questions %}

    {% for question in questions %}

      <p class="lead">
		{{ question.content }}
	  </p>

	  {% correct_answer_for_all question %}

      {% if question.user_answer %}
      <p>{% trans "Your answer" %}: {{ question|answer_choice_to_string:question.user_answer }}</p>
      {% endif %}

	  <p><strong>{% trans "Explanation" %}:</strong></p>
	  <div class="well " style="background-color: #fcf8e3;">
		<p>{{ question.explanation|safe }}</p>
	  </div>

	  <hr>

  {% endfor %}

  {% endif %}


{% endblock %}

quiz/templates/secret_page.html
{% extends 'base.html' %}

{% block body %}<br>
    <br>
    <br>
    <p>This is a secret page</p>
{% endblock %}

quiz/templates/single_complete.html
{% extends "base.html" %}
	{% load i18n %}
	
	{% load quiz_tags %}
	
	{% block title %} {{ quiz.title }} {% endblock %}
	{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}
	
	{% block body %}<br>
    <br>
    <br>
	<button type="button" class="btn btn-primary" onclick="location.href='{% url 'quiz:quiz_category_list_all'  %}'">{{ cat.category }}
        Quiz List</button>
	
        {% if user.is_authenticated %}
            <p>{% trans "You have already sat this exam and only one sitting is permitted" %}.</p>
        {% else %}
            <p>{% trans "This exam is only accessible to signed in users" %}.</p>
        {% endif %}
	
	{% endblock %}

quiz/templates/view_quiz_category.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Quizzes related to" %} {{ category.category }}{% endblock %}

{% block body %}<br>
    <br>
    <br>
<h1>{% trans "Quizzes in the" %} <strong>{{ category.category }} </strong>{% trans "category" %}</h1>

  {% with object_list as quizzes %}
    {% if quizzes %}
        <ul>
        {% for quiz in quizzes %}
            {% if quiz.category.category == "MCQ" %}
                <li>
                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'quiz:quiz_question' quiz_name=quiz.url %}'">{{ quiz.title }}</button>
                </li>
            {% elif quiz.category.category == "SUBJECTIVE" %}
                <li>
                    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'subjective:first' %}'">{{ quiz.title }}</button>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no quizzes" %}</p>
    {% endif %}
  {% endwith %}
{% endblock %}